superstrict
import brl.blitz
import maxgui.maxgui
CAL_TODAY%=4
CAL_PICKER%=8
CAL_HIDDEN%=2
CAL_WEEKEND%=1
TCalendar^TProxyGadget{
day_name$&[]&=mem:p("maxgui_proxygadgets_calendar_TCalendar_day_name")
month_name$&[]&=mem:p("maxgui_proxygadgets_calendar_TCalendar_month_name")
month_short$&[]&=mem:p("maxgui_proxygadgets_calendar_TCalendar_month_short")
month_days%&[]&=mem:p("maxgui_proxygadgets_calendar_TCalendar_month_days")
.map_dayfest:TMap&
.map_appointment:TMap&
._fest_data$&[]&
._fest_Desc$&[]&
._app_data$&[]&
._app_desc$&[]&
.lbl_day:TGadget&[]&
._icon:TPixmap&
._keephidden%&
.panel:TGadget&
.style%&
.old_day%&
.year_dec:TGadget&
.year_inc:TGadget&
.year:TGadget&
.month_dec:TGadget&
.month_inc:TGadget&
.month:TGadget&
.day_panel:TGadget&
.days:TGadget&[]&
.label:TGadget&[]&
.current_year%&
.current_month%&
.current_day%&
.day_wide%&
.day_height%&
.max_wide%&
.max_heigth%&
.data$&
.format$&
.pickday:TGadget&
.today:TGadget&
.min_w%&
.min_h%&
.max_w%&
.max_h%&
-SetMinimumSize%(mw%,mh%)="maxgui_proxygadgets_calendar_TCalendar_SetMinimumSize_ii"
-SetMaximumSize%(mw%,mh%)="maxgui_proxygadgets_calendar_TCalendar_SetMaximumSize_ii"
-SetFont%(fnt:TGuiFont="bbNullObject")="maxgui_proxygadgets_calendar_TCalendar_SetFont_TTGuiFont"
-SetLocale(_week$=$"",_month$=$"")="maxgui_proxygadgets_calendar_TCalendar_SetLocale_SS"
-SetHoliday(_day$=$"",_desc$=$"")="maxgui_proxygadgets_calendar_TCalendar_SetHoliday_SS"
-SetEnabled%(sta%=1)="maxgui_proxygadgets_calendar_TCalendar_SetEnabled_i"
-Close%()="maxgui_proxygadgets_calendar_TCalendar_Close"
-CleanUp%()="maxgui_proxygadgets_calendar_TCalendar_CleanUp"
-SetColor%(RED%,green%,blue%)="maxgui_proxygadgets_calendar_TCalendar_SetColor_iii"
-SetPixmap%(pix:TPixmap,flg%=8)="maxgui_proxygadgets_calendar_TCalendar_SetPixmap_TTPixmapi"
+Create:TCalendar(x%,y%,w%,h%,group:TGadget,style%=0)="maxgui_proxygadgets_calendar_TCalendar_Create_TTCalendar_iiiiTTGadgeti"
-Class%()="maxgui_proxygadgets_calendar_TCalendar_Class"
-SetToday%()="maxgui_proxygadgets_calendar_TCalendar_SetToday"
-GetText$()="maxgui_proxygadgets_calendar_TCalendar_GetText"
+ccGetCurrentDate$&[](ddate$)="maxgui_proxygadgets_calendar_TCalendar_ccGetCurrentDate_aS_S"
-DrawCalendar%(day_offset%=0,info$&[])="maxgui_proxygadgets_calendar_TCalendar_DrawCalendar_iaS"
-GetAppointment$&[](_Dat$=$"",index%=-1)="maxgui_proxygadgets_calendar_TCalendar_GetAppointment_Si"
-SetAppointment%(_dat$=$"",_des$=$"")="maxgui_proxygadgets_calendar_TCalendar_SetAppointment_SS"
-Activate%(command%)="maxgui_proxygadgets_calendar_TCalendar_Activate_i"
-SetDate%()="maxgui_proxygadgets_calendar_TCalendar_SetDate"
-SetText%(df$)="maxgui_proxygadgets_calendar_TCalendar_SetText_S"
-DateFormat$(df$)="maxgui_proxygadgets_calendar_TCalendar_DateFormat_S"
+eventHandler:Object(pID%,pData:Object,pContext:Object)="maxgui_proxygadgets_calendar_TCalendar_eventHandler_TObject_iTObjectTObject"
}="maxgui_proxygadgets_calendar_TCalendar"
ccConv_Date2Julian%(_data$=$"")="maxgui_proxygadgets_calendar_ccConv_Date2Julian"
ccDayOfTheWeek%(pjulian%)="maxgui_proxygadgets_calendar_ccDayOfTheWeek"
ccAnnoBisesto%(anno%=0)="maxgui_proxygadgets_calendar_ccAnnoBisesto"
CreateCalendar:TCalendar(x%,y%,w%=152,h%=191,group:TGadget="bbNullObject",_style%=0)="maxgui_proxygadgets_calendar_CreateCalendar"
SetCalendarAppointment%(calendar:TCalendar,date$=$"",app$=$"")="maxgui_proxygadgets_calendar_SetCalendarAppointment"
SetCalendarHoliday%(calendar:TCalendar,week$,description$)="maxgui_proxygadgets_calendar_SetCalendarHoliday"
SetCalendarLocale%(calendar:TCalendar,week$,month$)="maxgui_proxygadgets_calendar_SetCalendarLocale"
GetCalendarAppointment$&[](Calendar:TCalendar,date$=$"",index%=-1)="maxgui_proxygadgets_calendar_GetCalendarAppointment"
RemoveAppointments%(calendar:TCalendar,date$=$"",index%=-1)="maxgui_proxygadgets_calendar_RemoveAppointments"