superstrict
import brl.blitz
import maxgui.drivers
PBAR_STANDARD%=1
PBAR_INDICATOR%=8
PBAR_NOBORDER%=128
PBAR_SHOW%=2
PBAR_DISCRETE%=4
PBAR_RATING%=32
PBAR_ALERT%=16
PBAR_ACTIVE%=64
TPbar^TProxyGadget{
._void_pixmap:TPixmap&
._green_pixmap:TPixmap&
._RED_pixmap:TPixmap&
._YELLOW_pixmap:TPixmap&
.pixmap:TPixmap&
._star_pixmap:TPixmap&
.pixmap_flags%&
.panel:TGadget&
.panel_value:TGadget&
.panels:TGadget&[]&
.labels:TGadget&[]&
.tcolor%&[]&
.w%&
.h%&
._label_P:TGadget&
._label_V:TGadget&
._value#&
._value_warning%&
._value_critical%&
.STYLE%&
.flags%&
-SetFont%(fnt:TGuiFont="bbNullObject")="maxgui_proxygadgets_progressbar_TPbar_SetFont_TTGuiFont"
-GetText$()="maxgui_proxygadgets_progressbar_TPbar_GetText"
-CleanUp%()="maxgui_proxygadgets_progressbar_TPbar_CleanUp"
-SetProp%(_val%=0)="maxgui_proxygadgets_progressbar_TPbar_SetProp_i"
-SetRange%(_min%=0,_max%=10)="maxgui_proxygadgets_progressbar_TPbar_SetRange_ii"
-SetEnabled%(sta%=1)="maxgui_proxygadgets_progressbar_TPbar_SetEnabled_i"
-SetShow%(bool%)="maxgui_proxygadgets_progressbar_TPbar_SetShow_i"
-Class%()="maxgui_proxygadgets_progressbar_TPbar_Class"
-SetValue%(_val#=0.000000000#)="maxgui_proxygadgets_progressbar_TPbar_SetValue_f"
-SetColor%(R%=255,G%=255,B%=255)="maxgui_proxygadgets_progressbar_TPbar_SetColor_iii"
-SetTextColor%(R%=255,G%=255,B%=255)="maxgui_proxygadgets_progressbar_TPbar_SetTextColor_iii"
-SetPixmap%(pix:TPixmap,flags%)="maxgui_proxygadgets_progressbar_TPbar_SetPixmap_TTPixmapi"
+Create:TPbar(x%,y%,WIDTH%,HEIGHT%,group:TGadget,flags%=1)="maxgui_proxygadgets_progressbar_TPbar_Create_TTPbar_iiiiTTGadgeti"
+EventHook:Object(id%,data:Object,context:Object)="maxgui_proxygadgets_progressbar_TPbar_EventHook_TObject_iTObjectTObject"
}="maxgui_proxygadgets_progressbar_TPbar"
CreatePbar:TGadget(x%,y%,WIDTH%,HEIGHT%,group:TGadget,flags%=1)="maxgui_proxygadgets_progressbar_CreatePbar"