superstrict
import brl.blitz
import maxgui.maxgui
SPLIT_VERTICAL%=1
SPLIT_HORIZONTAL%=0
SPLITPANEL_MAIN%=0
SPLITPANEL_SIDEPANE%=1
SPLIT_FLIPPED%=2
SPLITPANEL_HANDLE%=2
SPLIT_ALL%=-1
SPLIT_LIMITPANESIZE%=2
SPLIT_CLICKTOTOGGLE%=32
SPLIT_RESIZABLE%=1
SPLIT_CANFLIP%=4
SPLIT_CANORIENTATE%=8
TSplitter^TProxyGadget{
JUMP%=200
SPLITSIDE_LEFT%=0
SPLITSIDE_RIGHT%=1
SPLITSIDE_TOP%=0
SPLITSIDE_BOTTOM%=1
intOrientationLocks%&[]&[]&[]&=mem:p("maxgui_proxygadgets_splitter_TSplitter_intOrientationLocks")
intSideToPanelMapping%&[]&[]&=mem:p("maxgui_proxygadgets_splitter_TSplitter_intSideToPanelMapping")
.strToggleTooltip$&
.intOrientation%&
.intMinPanelSpace%&
.intSavePanelSpace%&
.intBehavior%&
.intGutterSize%&
.intPanelSpace%&
.intMouseDown%&[]&
.intHasMoved%&
.intShouldUpdate%&
.pnlPanes:TGadget&[]&
.pnlSplitHandle:TGadget&
.divSplitHandle1:TGadget&
.divSplitHandle2:TGadget&
.gadParent:TGadget&
.pixHandle:TPixmap&[]&
-Create:TSplitter(pX%,pY%,pW%,pH%,pParent:TGadget,pOrientation%=1,pHandleSize%=10)="maxgui_proxygadgets_splitter_TSplitter_Create_iiiiTTGadgetii"
-GetOrientation%()="maxgui_proxygadgets_splitter_TSplitter_GetOrientation"
-SetOrientation(pOrientation%)="maxgui_proxygadgets_splitter_TSplitter_SetOrientation_i"
-SetBehavior(pBehavior%)="maxgui_proxygadgets_splitter_TSplitter_SetBehavior_i"
-GetBehavior%()="maxgui_proxygadgets_splitter_TSplitter_GetBehavior"
-GetPanel:TGadget(pPane%)="maxgui_proxygadgets_splitter_TSplitter_GetPanel_i"
-GetPanelSpace%(pPane%)="maxgui_proxygadgets_splitter_TSplitter_GetPanelSpace_i"
-SetPanelSpace(pPanelSpace%,flgSave%=1)="maxgui_proxygadgets_splitter_TSplitter_SetPanelSpace_ii"
-CleanUp%()="maxgui_proxygadgets_splitter_TSplitter_CleanUp"
-SetTooltip%(pTooltip$)="maxgui_proxygadgets_splitter_TSplitter_SetTooltip_S"
-GetTooltip$()="maxgui_proxygadgets_splitter_TSplitter_GetTooltip"
-SetTextColor%(pRed%,pGreen%,pBlue%)="maxgui_proxygadgets_splitter_TSplitter_SetTextColor_iii"
-SetColor%(pRed%,pGreen%,pBlue%)="maxgui_proxygadgets_splitter_TSplitter_SetColor_iii"
-SetSensitivity%(pSensitivity%)="maxgui_proxygadgets_splitter_TSplitter_SetSensitivity_i"
-GetSensitivity%()="maxgui_proxygadgets_splitter_TSplitter_GetSensitivity"
-ReapplyLocks()="maxgui_proxygadgets_splitter_TSplitter_ReapplyLocks"
-GetSideSpace%(pSide%)="maxgui_proxygadgets_splitter_TSplitter_GetSideSpace_i"
-DrawHandle()="maxgui_proxygadgets_splitter_TSplitter_DrawHandle"
-DrawPanes()="maxgui_proxygadgets_splitter_TSplitter_DrawPanes"
-ChangeOrientation(pOrientation%=-1)="maxgui_proxygadgets_splitter_TSplitter_ChangeOrientation_i"
-Toggle()="maxgui_proxygadgets_splitter_TSplitter_Toggle"
-eventHook:Object(pID%,pData:Object)="maxgui_proxygadgets_splitter_TSplitter_eventHook_iTObject"
+ShowNormalPointer()="maxgui_proxygadgets_splitter_TSplitter_ShowNormalPointer_v"
-ShowActivePointer()="maxgui_proxygadgets_splitter_TSplitter_ShowActivePointer"
-ShowDragPointer()="maxgui_proxygadgets_splitter_TSplitter_ShowDragPointer"
+eventHandler:Object(pID%,pData:Object,pContext:Object)="maxgui_proxygadgets_splitter_TSplitter_eventHandler_TObject_iTObjectTObject"
+RotatePixmap:TPixmap(pSrcPixmap:TPixmap)="maxgui_proxygadgets_splitter_TSplitter_RotatePixmap_TTPixmap_TTPixmap"
+BrightenPixmap:TPixmap(pSrcPixmap:TPixmap,pBrightness#=1.05#)="maxgui_proxygadgets_splitter_TSplitter_BrightenPixmap_TTPixmap_TTPixmapf"
+BrightenPixel%(pARGB%,pBrightness#=1.05#)="maxgui_proxygadgets_splitter_TSplitter_BrightenPixel_i_if"
+WhitenPixel%(pARGB%,pWhiteness#=0.8#)="maxgui_proxygadgets_splitter_TSplitter_WhitenPixel_i_if"
+MakeColourHandlePixmap:TPixmap(pRed%,pGreen%,pBlue%,pWidth%)="maxgui_proxygadgets_splitter_TSplitter_MakeColourHandlePixmap_TTPixmap_iiii"
}="maxgui_proxygadgets_splitter_TSplitter"
CreateSplitter:TSplitter(pX%,pY%,pW%,pH%,pParent:TGadget,pOrientation%=1,pHandleSize%=10)="maxgui_proxygadgets_splitter_CreateSplitter"
SplitterPanel:TGadget(splitter:TSplitter,panel%=0)="maxgui_proxygadgets_splitter_SplitterPanel"
SetSplitterPosition(splitter:TSplitter,position%,save%=1)="maxgui_proxygadgets_splitter_SetSplitterPosition"
SplitterPosition%(splitter:TSplitter)="maxgui_proxygadgets_splitter_SplitterPosition"
SetSplitterOrientation(splitter:TSplitter,orientation%=-1)="maxgui_proxygadgets_splitter_SetSplitterOrientation"
SplitterOrientation%(splitter:TSplitter)="maxgui_proxygadgets_splitter_SplitterOrientation"
SetSplitterBehavior(splitter:TSplitter,flags%=-1)="maxgui_proxygadgets_splitter_SetSplitterBehavior"
SplitterBehavior%(splitter:TSplitter)="maxgui_proxygadgets_splitter_SplitterBehavior"