superstrict
import brl.blitz
import maxgui.maxgui
import brl.max2d
import "common.bmx"
TOOLBARITEM_BUTTON%=1
TOOLBARITEM_SWITCH%=4
TOOLBARITEM_SEPARATOR%=99
TOOLBARITEM_TEXTFIELD%=2
TOOLBARITEM_SLIDER%=8
TOOLBARITEM_COMBOBOX%=3
TOOLBARITEM_LABEL%=5
TOOLBARITEM_TEXTBUTTON%=6
TOOLBARITEM_RADIOBUTTON%=7
tToolItem^Object{
font_size%&=mem:p("maxgui_proxygadgets_toolbarextra_tToolItem_font_size")
.gadget:TGadget&
.return_id%&
.status%&
.WIDTH%&
.enabled%&
.old_enabled%&
.icon_normal%&
.icon_select%&
.icon_current%&
.item_type%&
.toolbar:tToolbarExtra&
.tip$&
-Clear%()="maxgui_proxygadgets_toolbarextra_tToolItem_Clear"
+Create:tToolItem(id%,tb:tToolbarExtra,_x%,_TYPE%,_title$,_return_id%=-1,_icon%=-1)="maxgui_proxygadgets_toolbarextra_tToolItem_Create_TtToolItem_iTtToolbarExtraiiSii"
+CreateSeparator:tToolItem()="maxgui_proxygadgets_toolbarextra_tToolItem_CreateSeparator_TtToolItem"
-AddSubItem%(_title$=$"",_FLAGS%=0,_icon%=-1,_tip$=$"",_EXTRA:Object="bbNullObject")="maxgui_proxygadgets_toolbarextra_tToolItem_AddSubItem_SiiSTObject"
-SelectSubItem%(id%)="maxgui_proxygadgets_toolbarextra_tToolItem_SelectSubItem_i"
-SetSwitchIcon%(_normal%=0,_select%=0)="maxgui_proxygadgets_toolbarextra_tToolItem_SetSwitchIcon_ii"
-SetState%(_STATE%=0)="maxgui_proxygadgets_toolbarextra_tToolItem_SetState_i"
-SwapIcon%()="maxgui_proxygadgets_toolbarextra_tToolItem_SwapIcon"
-SetOver%()="maxgui_proxygadgets_toolbarextra_tToolItem_SetOver"
-SetNormal%()="maxgui_proxygadgets_toolbarextra_tToolItem_SetNormal"
-SetProp%(key$,value$)="maxgui_proxygadgets_toolbarextra_tToolItem_SetProp_SS"
}="maxgui_proxygadgets_toolbarextra_tToolItem"
tToolbarExtra^TProxyGadget{
item_width%&=mem:p("maxgui_proxygadgets_toolbarextra_tToolbarExtra_item_width")
list_tbextra:TList&=mem:p("maxgui_proxygadgets_toolbarextra_tToolbarExtra_list_tbextra")
.panel:TGadget&
.line:TGadget&
.line_up:TGadget&
.parent:TGadget&
.tfont:TGuiFont&
.tool_gadget:tToolItem&[]&
.colors@&[]&
.iconstrip:TIconStrip&
.grey_iconstrip:TIconStrip&
.light_iconstrip:TIconStrip&
.x%&
.name$&
.left_button:TGadget&
.right_button:TGadget&
.start_from%&
.last_from%&
.txt_rgb%&[]&
+Create:tToolbarExtra(parent:TGadget="bbNullObject",_iconstrip:TIconStrip="bbNullObject",_style%=0)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_Create_TtToolbarExtra_TTGadgetTTIconStripi"
-SetTextColor%(r%=255,g%=255,b%=255)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetTextColor_iii"
-SetColor%(r%=255,g%=255,b%=255)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetColor_iii"
-Activate%(cmd%=0)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_Activate_i"
-CleanUp%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_CleanUp"
-SetShow%(truefalse%=1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetShow_i"
-ReshapeAll%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ReshapeAll"
+eventHandler:Object(pID%,pData:Object,pContext:Object)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_eventHandler_TObject_iTObjectTObject"
-InsertItem%(index%,Text$=$"",tip$=$"",icon%=-1,extra:Object="bbNullObject",flags%=1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_InsertItem_iSSiTObjecti"
-SelectItem%(index%,t%=0)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SelectItem_ii"
-SetEnabled%(sta%=1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetEnabled_i"
-State%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_State"
-EnableAll%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_EnableAll"
-DisableAll%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_DisableAll"
-SetItem%(index%,Text$,tip$,icon%,extra:Object,flags%)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetItem_iSSiTObjecti"
-SetItemState%(index%=0,state%=1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetItemState_ii"
-ItemState%(index%=0)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ItemState_i"
-ItemCount%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ItemCount"
-ItemText$(index%=-1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ItemText_i"
-ItemIcon%(index%)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ItemIcon_i"
-ItemFlags%(index%)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ItemFlags_i"
-ItemExtra:Object(index%=-1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_ItemExtra_i"
-AddItem:tToolItem(_TYPE%=1,_title$=$"",_return_id%=-1,icon%=-1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_AddItem_iSii"
-AddSeparator%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_AddSeparator"
-RemoveItem%(index%=-1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_RemoveItem_i"
-Clear%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_Clear"
-SetIconStrip%(ics:TIconStrip)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetIconStrip_TTIconStrip"
-Class%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_Class"
-SetToolTipExtra%(ID%,_ti$=$"")="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetToolTipExtra_iS"
-SetFont%(Font:TGuiFont)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetFont_TTGuiFont"
-SetIcon%(ID%,_icon%=-1)="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SetIcon_ii"
-SelectedItem%()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SelectedItem"
-SelectedItems%&[]()="maxgui_proxygadgets_toolbarextra_tToolbarExtra_SelectedItems"
}="maxgui_proxygadgets_toolbarextra_tToolbarExtra"
CreateToolbarExtra:tToolbarExtra(_PARENT:TGadget="bbNullObject",_iconstrip:TIconStrip="bbNullObject",style%=0)="maxgui_proxygadgets_toolbarextra_CreateToolbarExtra"